trigger:
  - master

pool:
  vmImage: 'windows-2019'

variables:
  sqlprojFile: 'Database1.sqlproj'   # Path to the .sqlproj file
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: VSBuild@1
  inputs:
    solution: '$(sqlprojFile)'   # Build the .sqlproj file directly
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Listing files in $(System.DefaultWorkingDirectory):"
      Get-ChildItem -Recurse "$(System.DefaultWorkingDirectory)" | Where-Object { $_.Name -like "*.dacpac" }

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/Database1/bin/$(buildConfiguration)'  # Correct output folder
    Contents: '*.dacpac'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dacpac'
    publishLocation: 'Container'
