trigger:
- master

pool:
  name: 'Windows-Based'

variables:
  solution: '**/Database1.sln' # Update to your solution file
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# Install NuGet (ensures package manager is available)
- task: NuGetToolInstaller@1

# Restore NuGet packages for the solution
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# Build the solution using Visual Studio
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Run tests (if any)
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Copy the .dacpac file from the build output
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)' # Default working directory for the build agent
    Contents: '**/bin/Release/*.dacpac'               # Match the .dacpac file anywhere under the bin\Release folder
    TargetFolder: '$(Build.ArtifactStagingDirectory)' # Artifact staging directory

# Publish the artifact for deployment or other pipelines
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)' # The folder containing the .dacpac
    ArtifactName: 'drop'
    publishLocation: 'Container'
