trigger:
- mater

pool:
  vmImage: 'windows-latest'


stages:
- stage: Build
  displayName: "Build DACPAC"
  jobs:
  - job: Build
    displayName: "Build DACPAC"
    steps:
    - task: NuGetToolInstaller@1
      displayName: "Install NuGet"

    - task: NuGetCommand@2
      displayName: "Restore NuGet Packages"
      inputs:
        command: 'restore'
        restoreSolution: '$(Build.SourcesDirectory)/Database1.sln'  # Path to solution file in root

    - task: VSBuild@1
      displayName: "Build SQL Project"
      inputs:
        solution: '$(Build.SourcesDirectory)/Database1.sln'  # Path to solution file in root
        msbuildArgs: '/p:DeployOnBuild=true /p:Configuration=Release'
        platform: 'Any CPU'
        configuration: 'Release'


    - task: PublishBuildArtifacts@1
      displayName: "Publish DACPAC Artifact"
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Use Artifact Staging Directory
        artifactName: 'DACPAC'
        publishLocation: 'Container'
