trigger:
  - master

pool:
  vmImage: 'windows-latest'

variables:
  sqlprojFile: 'Database1.sqlproj'  # The .sqlproj file in the root directory
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(sqlprojFile)'  # Restoring dependencies for the .sqlproj file

- task: VSBuild@1
  inputs:
    solution: '$(sqlprojFile)'  # Building the SQL project
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/bin/$(buildConfiguration)'  # Output directory for .dacpac
    Contents: '*.dacpac'  # Include only .dacpac files
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dacpac'
    publishLocation: 'Container'
