trigger:
- master  # Update this with the actual branch name if it's different.

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  displayName: "Build DACPAC"
  jobs:
  - job: Build
    displayName: "Build DACPAC"
    steps:
    - task: NuGetToolInstaller@1
      displayName: "Install NuGet"

    - task: NuGetCommand@2
      displayName: "Restore NuGet Packages"
      inputs:
        command: 'restore'
        restoreSolution: '$(Build.SourcesDirectory)/Database1.sln'  # Path to solution file

    - task: VSBuild@1
      displayName: "Build SQL Project"
      inputs:
        solution: '$(Build.SourcesDirectory)/Database1.sln'  # Path to solution file
        msbuildArgs: '/p:DeployOnBuild=true /p:Configuration=Release /p:OutputPath=$(Build.ArtifactStagingDirectory)'  # Ensure output goes to Artifact Staging Directory
        platform: 'Any CPU'
        configuration: 'Release'

    - task: PublishBuildArtifacts@1
      displayName: "Publish DACPAC Artifact"
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Use the staging directory for artifacts
        artifactName: 'DACPAC'
        publishLocation: 'Container'
