trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  sqlServerName: "om-db-testing.database.windows.net"
  sqlDatabaseName: "db-auto"
  sqlUsername: "omnagare"
  sqlPassword: "Ironman7028@"

stages:
- stage: Build
  displayName: "Build DACPAC"
  jobs:
  - job: Build
    displayName: "Build DACPAC"
    steps:
    - task: NuGetToolInstaller@1
      displayName: "Install NuGet"

    - task: NuGetCommand@2
      displayName: "Restore NuGet Packages"
      inputs:
        command: 'restore'
        restoreSolution: '$(Build.SourcesDirectory)/Database1.sln'  # Path to solution file in root

    - task: VSBuild@1
      displayName: "Build SQL Project"
      inputs:
        solution: '$(Build.SourcesDirectory)/Database1.sln'  # Path to solution file in root
        msbuildArgs: '/p:DeployOnBuild=true /p:Configuration=Release'
        platform: 'Any CPU'
        configuration: 'Release'

    - task: PublishBuildArtifacts@1
      displayName: "Publish DACPAC Artifact"
      inputs:
        pathtoPublish: '$(Build.SourcesDirectory)/bin/Release'  # Ensure DACPAC is in bin/Release
        artifactName: 'DACPAC'

- stage: Deploy
  displayName: "Deploy to Azure SQL"
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: "Deploy DACPAC to Azure SQL"
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: "Download Build Artifacts"
      inputs:
        buildType: 'current'
        downloadType: 'specific'
        artifactName: 'DACPAC'
        downloadPath: '$(Pipeline.Workspace)/DACPAC'

    - task: SqlAzureDacpacDeployment@1
      displayName: "Deploy DACPAC"
      inputs:
        azureSubscription: "Ballotnow-Backend-Service"
        ServerName: "$(sqlServerName)"
        DatabaseName: "$(sqlDatabaseName)"
        SqlUsername: "$(sqlUsername)"
        SqlPassword: "$(sqlPassword)"
        DacpacFile: '$(Pipeline.Workspace)/DACPAC/*.dacpac'
        DeployType: 'DacpacTask'
