trigger:
  - master

pool:
  vmImage: 'windows-latest'

variables:
  sqlprojFile: 'Database1.sqlproj'  # Path to .sqlproj file
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'  # Restore NuGet packages

- task: VSBuild@1
  inputs:
    solution: '$(sqlprojFile)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Debugging step to locate the .dacpac file
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Get-ChildItem -Recurse "$(System.DefaultWorkingDirectory)" | Where-Object { $_.Name -like "*.dacpac" }

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/Database1/bin/$(buildConfiguration)'  # Adjusted folder path
    Contents: '*.dacpac'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dacpac'
    publishLocation: 'Container'
