trigger:
  - master

pool:
  vmImage: 'windows-latest'

variables:
  sqlprojFile: '**/Database1.sqlproj'  # Targeting the .sqlproj file
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'  # Ensure NuGet dependencies for the solution are restored

- task: VSBuild@1
  inputs:
    solution: '$(sqlprojFile)'  # Building the .sqlproj file
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/bin/$(buildConfiguration)/*.dacpac'  # Locate and copy the .dacpac file
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dacpac'
    publishLocation: 'Container'
